### ISSUE TITLE
This isnt UDP 

### ISSUE THREAD

**Issue by levonravel** [darkguy2008/SharpRUDP#5]
Your using a TCPListener for your supposed reliable udp library. This is a joke right? anycase you want to see a real udp library look here https://github.com/RevenantX/LiteNetLib pure udp socket with reliable, sequenced, unreliable etc. Yours is not rupd because your still involving a tcp listener.

**Comment by darkguy2008** [comment]
Dude, what the fuck? I'm using sockets. If you just want to promote your project then get the hell out of here as it's really obvious you don't know what the fuck are you talking about.
